### ISSUE TITLE
Error accessing travis-ci log

### ISSUE THREAD

**Issue by davidpv1** [madnight/docker-alpine-wkhtmltopdf#18]
When trying to access to `https://api.travis-ci.org/v3/job/606718795/log.txt` return 404 status. 

View next image: 
![image](https://user-images.githubusercontent.com/73908004/172954649-fe9f8abc-546c-4ec3-9a86-fe5753b1f07c.png)

**Comment by blunckr-aj** [comment]
I'm running into the same thing. For now, I've hard-coded the old hash value in my Dockerfile.

**Comment by Damienbleucerise** [comment]
Hello @blunckr-aj can you show us your Dockerfile, I can't find how to do it like you. 
Thank you for your time have a nice day.

**Comment by Damienbleucerise** [comment]
Hello @blunckr-aj , can you show us what you put in your Dockerfile, I'm having some problems and I can't seem to solve them. Thank you for your time, have a nice day.

**Comment by blunckr-aj** [comment]
```
COPY --from=madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10-606718795 \
    /bin/wkhtmltopdf /bin/wkhtmltopdf

ENV BUILD_LOG=https://api.travis-ci.org/v3/job/606718795/log.txt

# The BUILD_LOG is no longer accessible, instead we're using a hash we know is
# valid from an earlier build
RUN [ "$(sha256sum /bin/wkhtmltopdf | awk '{ print $1 }')" == "06139f13500db9b0b4373d40ff0faf046e536695fa836e92f41d829696d6859f" ]
```

That's what I did. Of course that hash will only work for the 606718795 version. I found the hash in a docker container we built before the log became inaccessible.

**Comment by Damienbleucerise** [comment]
Thank you very much, it works perfectly.

**Comment by madnight** [comment]
[blunckr-aj](https://github.com/blunckr-aj) thanks for your fix, I'll add it to master.

**Comment by madnight** [comment]
https://github.com/madnight/docker-alpine-wkhtmltopdf/commit/a2598ab3d3c6f853417692c96214474bb6b9738f
