### ISSUE TITLE
Problem with metric CSS dimensions

### ISSUE THREAD

**Issue by mikehaertl** [madnight/docker-alpine-wkhtmltopdf#2]
For PDF styling I use `cm` dimensions in my CSS which usually works fine.

But the version from the docker-alpine-wkhtmltopdf image somehow seems to scale up the dimenions by some factor.

Here's a simple example:

```html
<!DOCTYPE html>
<html><head>
<style>
body {
    border: 1px solid red;
    margin:         0;
    padding:        0;
    width:          20cm;
    height:         29cm;
}
</style>
</head>
<body>
</body></html>
```

The default page size A4 is roughly 29.7 cm by 21 cm. So the following command should render a red bordered box on that fits on the page:

```
wkhtmltopdf --no-outline \
  --encoding 'UTF-8' \
  --margin-top '0' \
  --margin-right '0' \
  --margin-bottom '0' \
  --margin-left '0' \
  --disable-smart-shrinking \
  test.html test.pdf
```

The correct result with wkhtmltopdf 0.12.5 on my Ubuntu box:

![a4_border_correct](https://user-images.githubusercontent.com/675062/47933751-b0c68280-ded5-11e8-9e73-5ff7a093f3c5.png)

And this is the result with the docker-alpine image. The red box exceeds the A4 page to the right and to the bottom and continues on a second page.

![a4_border_incorrect](https://user-images.githubusercontent.com/675062/47934057-950fac00-ded6-11e8-9264-6fdcac06dfd7.png)

**Comment by madnight** [comment]
Hmm that's interesting, on my Arch Linux System I get the following result with wkhtmltopdf `0.12.5`: 

![image](https://user-images.githubusercontent.com/10064471/48090627-bb4f8780-e207-11e8-842f-87b1a376cd09.png)

And with docker-alpine-wkhtmltopdf (same as you):

![image](https://user-images.githubusercontent.com/10064471/48090785-2436ff80-e208-11e8-9d79-f37ab4298da5.png)

So there must be something other than the binary parameters that causes the result differences. Maybe compile flags or environment variables or installed external dependencies (like fonts).

**Comment by mikehaertl** [comment]
@madnight Is this solved?

**Comment by madnight** [comment]
@mikehaertl As far as I understand the issue is related to the version `0.12.4-dev (with patched qt)`. I updated the binary to 0.12.5 yesterday, a version that works for us under Ubuntu and Arch. So I guess it is, you can check that by building a new docker image with the current master. Let me know if the issue still exists with 0.12.5, then I will reopen this issue for sure.

**Comment by mikehaertl** [comment]
Hmm, the latest version on docker hub is a month old: https://hub.docker.com/r/madnight/docker-alpine-wkhtmltopdf/tags

Could you push a new version? Then I can check if the problem is still there.

**Comment by madnight** [comment]
Sure, once done I'll notify you.

**Comment by madnight** [comment]
@mikehaertl Alright I just pushed: `0.12.5-alpine3.10` and updated `latest`

**Comment by mikehaertl** [comment]
Tested it and confirm: problem is fixed indeed. Thanks!
