### ISSUE TITLE
wkhtmltopdf 0.12.5

### ISSUE THREAD

**Issue by oadam** [madnight/docker-alpine-wkhtmltopdf#5]
Could you update wkhtmltopdf to the latest version ?

**Comment by madnight** [comment]
At the moment I cannot find a working Dockerfile with wkhtmltopdf and qt patches and Alpine 1.10.

**Comment by madnight** [comment]
Maybe this one: https://github.com/Surnet/docker-wkhtmltopdf/blob/master/archive/alpine-wkhtmltopdf/Dockerfile_3.10-0.12.5-full

**Comment by madnight** [comment]
Alright the surnet Dockerfile works fine. I would recommend you to use
 `surnet/alpine-wkhtmltopdf:3.10-0.12.5-small`

**Comment by madnight** [comment]
The binary version is now: `wkhtmltopdf 0.12.5 (with patched qt)`
