### ISSUE TITLE
Script the compilation of wkhtmltopdf

### ISSUE THREAD

**Issue by oadam** [madnight/docker-alpine-wkhtmltopdf#6]
It would be better if the compilation of wkhtmltopdf was included in the repository.

The compilation could happen in a separate container using a [multistage build](https://docs.docker.com/develop/develop-images/multistage-build/). The resulting container would only contain the compiled binary.

**Comment by madnight** [comment]
That's true, that would be better. However, there is already such an approach https://github.com/Surnet/docker-wkhtmltopdf/blob/master/Dockerfile-alpine.template

This is the Dockerfile that I used to compile the binary https://github.com/alloylab/Docker-Alpine-wkhtmltopdf/blob/master/Dockerfile

This Dockerfile is unmaintained and 4 years old, not even sure if it still compiles.

**Comment by madnight** [comment]
Okay the compilation is now scripted.  This is the Dockerfile  
https://github.com/madnight/docker-alpine-wkhtmltopdf/blob/master/src/Dockerfile  
to build the binary.

And this is the Travis CI build log for the the binary 
https://api.travis-ci.org/v3/job/585241708/log.txt
https://travis-ci.org/madnight/docker-alpine-wkhtmltopdf/builds/585241704

Checksum (sha256):   
`1a9eef2321bc5650b619203f6e0c8cde675ccfb7e77d68c5c0dbfe7e25978b40`

Checksum verification
https://github.com/madnight/docker-alpine-wkhtmltopdf/blob/d0f6b39891dbb928cc4242efa2e12735baf4bed7/Dockerfile#L13-L15

So the compilation process is now fully transparent.
