### ISSUE TITLE
wkhtmltopdf binary removed? how to download it?

### ISSUE THREAD

**Issue by TilakPutta-zz** [madnight/docker-alpine-wkhtmltopdf#7]
/bin/sh -c wget https://github.com/madnight/docker-alpine-wkhtmltopdf/raw/master/wkhtmltopdf -O /bin/wkhtmltopdf

I have this in my docker, now that file is removed! where to find it .. so that at least i can keep it in my s3 and serve.

**Comment by madnight** [comment]
Hi, you can use this URL (should work forever).
https://github.com/madnight/docker-alpine-wkhtmltopdf/raw/c4ece5170c9436404f35dbe8a385c1711aa99212/wkhtmltopdf

Recommendation: Don't fetch from `master`. Use commit hashes and perma links, everything else is subject to change.

**Comment by madnight** [comment]
`COPY --from=madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10 /bin/wkhtmltopdf /bin/wkhtmltopdf`

would also do, if you build a Dockerfile
