### ISSUE TITLE
My docker build -t alpine-wkhtmltopdf . failed

### ISSUE THREAD

**Issue by pedrobacchini** [madnight/docker-alpine-wkhtmltopdf#8]
Sending build context to Docker daemon  34.82kB
Step 1/7 : FROM alpine:3.10
 ---> 965ea09ff2eb
Step 2/7 : MAINTAINER Fabian Beuke <mail@beuke.org>
 ---> Using cache
 ---> 030f10a94fe5
Step 3/7 : RUN apk add --update --no-cache     libgcc libstdc++ libx11 glib libxrender libxext libintl     ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family
 ---> Using cache
 ---> df8019352057
Step 4/7 : COPY --from=madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10     /bin/wkhtmltopdf /bin/wkhtmltopdf
 ---> Using cache
 ---> 84081596742b
Step 5/7 : ENV BUILD_LOG=https://api.travis-ci.org/v3/job/585241708/log.txt
 ---> Using cache
 ---> a1ee00a4ad70
Step 6/7 : RUN [ "$(sha256sum /bin/wkhtmltopdf | awk '{ print $1 }')" ==       "$(wget -q -O - $BUILD_LOG | sed -n '14121p' | awk '{ print $1 }')" ]
 ---> Running in 056655fdbb3c
The command '/bin/sh -c [ "$(sha256sum /bin/wkhtmltopdf | awk '{ print $1 }')" ==       "$(wget -q -O - $BUILD_LOG | sed -n '14121p' | awk '{ print $1 }')" ]' returned a non-zero code: 1

**Comment by madnight** [comment]
I'll check that out, seems to be an issue with the checksum, guess something has changed in the build.

**Comment by madnight** [comment]
Should be fixed now https://github.com/madnight/docker-alpine-wkhtmltopdf/commit/a88f4eb36d3d942f7e6d7079f9bc4774ef750cf3

**Comment by pedrobacchini** [comment]
worked perfectly. thx.
