### ISSUE TITLE
alpine 3.11

### ISSUE THREAD

**Issue by ayazzali** [madnight/docker-alpine-wkhtmltopdf#9]
can you do it on alpine3.11?

**Comment by madnight** [comment]
yup should work, I'll try to compile a version, probably tomorrow

**Comment by ayazzali** [comment]
cool. i tried just edit first line on Dockerfile https://github.com/madnight/docker-alpine-wkhtmltopdf/blob/a88f4eb36d3d942f7e6d7079f9bc4774ef750cf3/Dockerfile#L1 to FROM alpine:3.11

it worked!)

**Comment by ayazzali** [comment]
do you know why it dont see css/images ? (i use Rotativa in c#)
